[package]
name = "scalarc-bsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
log = "0.4.20"
serde_json = "1.0.113"
thiserror = "1.0.56"
