[workspace]
resolver = "2"
members = [
  "scalarc-ast",
  "scalarc-build",
  "scalarc-syntax",
  "scalarc-parser",
  "scalarc-typer",
  "scalarc-lsp",
]

[workspace.dependencies]
scalarc-parser = { path = "scalarc-parser" }
scalarc-build = { path = "scalarc-build" }
