[package]
name = "scalarc-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
rowan = "0.15.15"
scalarc-ast = { path = "../scalarc-ast" }
thiserror = "1.0.56"
