[package]
name = "scalarc-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
parking_lot = "0.12.1"
pretty_assertions = "1.4.0"
