[package]
name = "scalarc-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
salsa = "0.16.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
